### ISSUE TITLE
Copy to clipboard button border radius

### ISSUE THREAD

**Issue by kuwood** [EQuimper/MyOwnChallenge-UrlShort#2]
When hovering on copy to clipboard it loses its border-radius

**Comment by EQuimper** [comment]
Yes but I think this is bootstrap who make this :( I dont know why

**Comment by kuwood** [comment]
Ahh I see, yea it is bootstrap. In that case just throw this in your styles.css it will override bootstraps css for that button. `#btn-short {
  border-top-right-radius: 6px;
  border-bottom-right-radius: 6px;
}`

**Comment by EQuimper** [comment]
Perfect done ;) Thank you again
